# Initialize simulation

variable nsteps index 100000
variable nevery equal 1 # frequency (in number of steps) in which qeq is run to optimize charges
variable temp equal 4000.0 # starting temperature (should equilibrate to ~ 1/2 this value)
variable coulcut equal 20 # global coulomb cutoff (see pair_style), used in QEq fix
variable nrep equal 16 # cell multiple
variable a equal 3.16 # bcc lattice vector (a) for tungsten
variable streitzalpha equal 0.2
units metal
atom_style charge

boundary p p p

lattice bcc ${a} # bcc
variable nx equal ${nrep}
variable ny equal ${nrep}
variable nz equal ${nrep}
lattice         bcc ${a}
region          box block 0 ${nx} 0 ${ny} 0 ${nz}

create_box      2 box
create_atoms    2 box

# Add this section to create 10 random nitrogen atoms (type 2)
region nitrogen_region block 0 ${nx} 0 ${ny} 0 ${nz} units lattice
create_atoms 1 random 10 12345 nitrogen_region
mass 1 14.0067 # Mass for nitrogen
mass 2 183.84 # Mass for tungsten

set group all charge 1.e-100
include WN_pot.mod
#pair_style hybrid/overlay pace product
#pair_coeff * * pace WN_pot.yace N W

#Replicate
#replicate 3 3 3 
# Define computes and variables to view from simulation
compute eatom all pe/atom
compute energy all reduce sum c_eatom
compute satom all stress/atom NULL
compute str all reduce sum c_satom[1] c_satom[2] c_satom[3]
variable press equal (c_str[1]+c_str[2]+c_str[3])/(3*vol)


# Tell 'thermo' what values should be printed
thermo_style custom step temp epair c_energy etotal press v_press
thermo 100
thermo_modify norm yes
# Prepare for NVE MD run
timestep 0.5e-3
neighbor 1.0 bin
neigh_modify once no every 1 delay 0 check yes

fix 1q all qeq/slater ${nevery} ${coulcut} 1.0e-6 100 coul/streitz alpha ${streitzalpha}

dump 2min all cfg 1 min.*.cfg mass type xs ys zs
run             0

undump          2min


dump            minats all custom 1 minqdump.xyz id type  x y z q

#fix             22 everything setforce 0 0 0
fix 1 all box/relax iso 0.0 vmax 0.001
minimize        0 0 100 1000
unfix           1
undump          minats

velocity all create 2000.0 4928459 rot yes dist gaussian
dump 4b all custom 10 dump.xyz id type x y z q

fix 1 all nve
run             ${nsteps}
