# This file was generated by FitSNAP.
# Hash: ae73c556e21728af5558c083907c4ae6

pair_style hybrid/overlay coul/streitz 10.0 ewald pace product
pair_coeff * * coul/streitz NW_auto.0000.streitz N W
pair_coeff * * pace WN_pot.yace N W
kspace_style ewald 1.0e-6
