# This file was generated by FitSNAP.
# Hash: 0eefaef59554ecac39aae4dcc73dc789

pair_style hybrid/overlay coul/streitz 10.0 ewald pace product
pair_coeff * * coul/streitz NW_auto.0000.streitz N W
pair_coeff * * pace WN_pot.yace N W