# This file was generated by FitSNAP.
# Hash: f397fe7632645ef6be05ea4e36c4bccf

pair_style hybrid/overlay zbl 2.450000 2.800000 zbl 2.800000 3.200000 zbl 3.213000 3.672000 coul/streitz 10.0 ewald pace product
pair_coeff 1 1 zbl 1    7 7
pair_coeff 1 2 zbl 2    7 74
pair_coeff 2 2 zbl 3    74 74
pair_coeff * * coul/streitz NW_auto.0000.streitz N W
pair_coeff * * pace WN_pot.yace N W